version: "3.9"
services:
  users-server:
    build: ../source/users-server
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ../source/users-server:/app/out
