version: "3.9"

services:
  
  dnevnik-web:
    build: 
      context: ../source/dnevnik-web
      dockerfile: Dockerfile
    volumes:
      - ../source/dnevnik-web:/app
    ports:
      - '80:5173'
  
  users-server:
    build: ../source/users-server
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ACCESS_TOKEN_KEY=0123456789qwertyuiopasdfghjklzxcvbnm
      - ConnectionStrings__UsersDb=Host=users-db:5432; Database=users-db; Username=postgres;Password=postgres
      - IN_MEM_DB=false
    volumes:
      - ../source/users-server:/app/out

  users-db:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
      - users-db:/var/lib/postgresql/data

volumes:
  users-db:
    driver: local
    
